#!/bin/sh
#
# update-model-manifest
#

set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

MANIFEST_FPATH="${MANIFEST_FPATH}"
MODEL_IMAGE_NAME="${IMAGE_NAME}"
MODEL_VERSION="${MODEL_VERSION}"
SEQ_HASH="${SEQ_HASH}"

cat "${MANIFEST_FPATH}" | sed -e "s|${MODEL_IMAGE_NAME}:.*\",|${MODEL_IMAGE_NAME}:${MODEL_VERSION}\",|" | sed -e "s|${MODEL_NAME}-.*-dpl\"|${MODEL_NAME}-${MODEL_VERSION}-${SEQ_HASH}-dpl\"|" | sed -e "s|${MODEL_NAME}-.*-pred\"|${MODEL_NAME}-${MODEL_VERSION}-${SEQ_HASH}-pred\"|" | tee "${MANIFEST_FPATH}".tmp

mv "${MANIFEST_FPATH}".tmp "${MANIFEST_FPATH}"
